export const SET_MOVIES = 'SET_MOVIES';
export const SWITCH_BANNER = 'SWITCH_BANNER';
export const MOVIE_FILTER = 'MOVIE_FILTER';
export const MOVIES_SORTED_BY_TITLE = 'MOVIES_SORTED_BY_TITLE';
export const MOVIES_SORTED_BY_DATE = 'MOVIES_SORTED_BY_DATE';
export const MOVIES_SORTED_BY_RATING = 'MOVIES_SORTED_BY_RATING';
export const ADD_MOVIE = 'ADD_MOVIE';
export const DELETE_MOVIE = 'DELETE_MOVIE';
