export const SET_MOVIES = 'SET_MOVIES';
export const SET_MOVIE_INSTANCE = 'SET_MOVIE_INSTANCE';
export const SET_MOVIE = 'SET_MOVIE';
export const MOVIES_SORTED_BY_TITLE = 'MOVIES_SORTED_BY_TITLE';
export const MOVIES_SORTED_BY_DATE = 'MOVIES_SORTED_BY_DATE';
export const MOVIES_SORTED_BY_RATING = 'MOVIES_SORTED_BY_RATING';
